on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches: main

name: Quint

permissions:
  contents: read

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      id-token: write
    outputs:
      specs: ${{ steps.filter.outputs.specs }}
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: block
          policy: global-allowed-endpoints-policy

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            specs:
              - 'specs/**'

  quint-typecheck:
    name: Typecheck
    needs: changes
    if: ${{ needs.changes.outputs.specs == 'true' || github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: block
          policy: global-allowed-endpoints-policy

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: "18"
      - run: npm install -g @informalsystems/quint
      - run: find specs/ -name '*.qnt' | ./scripts/quint-forall.sh typecheck

  quint-test:
    name: Test
    needs: changes
    if: ${{ needs.changes.outputs.specs == 'true' || github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    env:
      MAX_SAMPLES: 100
    permissions:
      id-token: write
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: block
          policy: global-allowed-endpoints-policy

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: "18"
      - run: npm install -g @informalsystems/quint
      - run: find specs/ -name '*Test.qnt' | ./scripts/quint-forall.sh test --max-samples $MAX_SAMPLES
